### ISSUE TITLE
各种异常崩溃报错内存泄漏空指针，望修复。

### ISSUE THREAD

**Issue by TxcA** [hc1234/MyHcUtils#1]
@hc1234 #hi, Hc.

**Comment by hc1234** [comment]
放屁，一个错一百万！截图领钱

**Comment by TxcA** [comment]
![8](https://user-images.githubusercontent.com/15992858/79553682-6dfb6900-80cf-11ea-891e-ad57d1299275.jpg)
写什么代码，来lu撸

**Comment by TxcA** [comment]
> 放屁，一个错一百万！截图领钱

优秀
